/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rclp9;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.junit.jupiter.api.Test;

import processing.core.*;

class RCLP9Test extends PApplet {
    private RCLP9 rclp9 = new RCLP9(this, "test_node_rclp9");
    private int counter;

    @Test
    public void testCreateAndDispose() {
        rclp9.createPublisher(std_msgs.msg.String.class, "test_topic");
        assertEquals(rclp9.getNode().getHandle(), rclp9.getPublisher().getNodeReference().get().getHandle());
        assertNotEquals(0, rclp9.getPublisher().getNodeReference().get().getHandle());
        assertNotEquals(0, rclp9.getPublisher().getHandle());
        assertEquals(1, rclp9.getNode().getPublishers().size());

        rclp9.dispose();
        assertEquals(0, rclp9.getPublisher().getHandle());
        assertEquals(0, rclp9.getNode().getPublishers().size());
    }

    @Test
    public final void testFunctionalPublisher() {
        counter = 0;
        rclp9.createPublisher(std_msgs.msg.String.class, "test_topic");
        rclp9.createWallClockTimer(500, this::timerCallback);
        rclp9.spinPublisherOnce();
    }

    private void timerCallback() {
        var message = new std_msgs.msg.String();
        message.setData("Hello, world! " + this.counter);
        this.counter++;
        System.err.println("Publishing: [" + message.getData() + "]");
        rclp9.publish(message);
    }
}
